### ISSUE TITLE
pyinstaller error

### ISSUE THREAD

**Issue by Fish-pro** [python/importlib_resources#229]
see that
```shell
44109 INFO: Loading module hook "hook-importlib_resources.py"...
Unable to find "/opt/app-root/lib/python3.6/site-packages/importlib_resources/version.txt" when adding binary and data files.
```

**Comment by FFY00** [comment]
See #62

**Comment by jaraco** [comment]
I wonder what causes `hook-importlib_resources.py` to search for `importlib_resources/version.txt`. In older versions (prior to 1.2), this package had a version.txt. Since `v3.0.0`, this package recommends to simply query package metadata (`importlib.metadata.version('importlib_resources')`).

There's not much this project can do to present the version as a text file (without maintaining the version duplicately), but if there's a strong use-case to ensure that file exists for compatibility, feel free to present it.
