### ISSUE TITLE
stock importlib.resources on python 3.9 importlib.resources.files does not work in zipapp

### ISSUE THREAD

**Issue by franzhaas** [python/importlib_resources#281]
Dear all,

This is not a bug of importlib_resources, but I still hope that the community here can help me.

I experience in my environment that importlib.resources.files works on python 3.10 and 3.11.

On python 3.6, 3.7 and 3.8 it does not exist -> therefore I use importlib_resources.

On python 3.9 it exists, and works in a regular environment, but not in a zipapp. 

Again -> I use importlib_resources. 

Is this to be expected? Am I misunderstanding something?

**Comment by FFY00** [comment]
Hi, it is not expected. Can you share an example of how it doesn't work?

**Comment by franzhaas** [comment]
For me this example works in 3.10, 3.11 but not 3.9.13


from  importlib.resources import files

with files("res.res").joinpath("a.txt").open('r', encoding="utf-8") as f:
    print(f.read())


Thanks for giving it a look...

**Comment by franzhaas** [comment]
[res.zip](https://github.com/python/importlib_resources/files/11090024/res.zip)

Here is an example of a zipapp with stock importlib, which fails with 3.9 ...

**Comment by pekkaklarck** [comment]
Here's a workaround:
```python
from importlib.resources import files
from platform import python_version_tuple, system

path = files("res.res").joinpath("a.txt")
if system() == 'Windows' and python_version_tuple()[:2] == ('3', '9'):
    path.at = path.at.replace('\\', '/')
text = path.read_text(encoding='utf-8')
print(text)
```

**Comment by jaraco** [comment]
From the compatibility matrix in the readme, you can see that `importlib_resources` 1.3 was used for Python 3.9 and `importlib_resources` 5.0 was used in Python 3.10, so one of those changes probably addressed the shortcoming. I suspect it was the changes in v2.0.0. In Python 3.9, the files were resolved with [fallback_resources](https://github.com/python/cpython/blob/7cb3a4474731f52c74b19dd3c99ca06e227dae3b/Lib/importlib/_common.py#L17-L25), and by Python 3.10, the resources were supplied by a [native reader that handled the path separators](https://github.com/python/cpython/blob/425065bb002b9cbf9c12f61a6f3102f2ce2b8d14/Lib/importlib/readers.py#L27-L31).



> it might make sense to add a note to `importlib.resources.files()` docs about it not working on Windows with Python 3.9.

Since Python 3.9 only gets security fixes, I'm inclined to say it's not worth adding this detail to the docs (and may not be allowed).

> Is this to be expected?

It is expected that using later versions of `importlib_resources` on older Pythons provides a newer experience, so that's the recommended workaround.
