### ISSUE TITLE
Removal of legacy API 

### ISSUE THREAD

**Issue by soxofaan** [python/importlib_resources#284]
I'm still in the process of figuring out this issue, so apologies if this is a duplicate or discussed elsewhere.

one of our CI builds started failing with 
```
module 'importlib_resources' has no attribute 'path'
```
and apparently version 6.0.0 released last week dropped this legacy function and others #80 #282

(Background info about our usage: we're currently on python 3.8 and leverage `importlib_resources` as workaround for a fix that's only fixed in python 3.10 stdlib importlib.resources: https://bugs.python.org/issue44137. )

If I understand correctly stdlib's [importlib.resources.path](https://docs.python.org/3.11/library/importlib.resources.html#importlib.resources.path), is only officially deprecated since python3.11.
So that means that importlib_resources v6.0.0 can not be used as a pure drop-in backport of `importlib.resources` anymore because of the absence of this deprecated API. Is that intended?

**Comment by jaraco** [comment]
It is intended that the 6.0 and later releases no longer support the legacy functions. It's still intended to be a pure drop-in replacement for non-legacy behavior and still supports bugfixes for the legacy functions (if needed) in the 5.x line. But you're right - if you are depending on the legacy behavior and need features only available in later releases, you'll have to be more selective about the versions of `importlib_resources` that are viable for your use-case. It should be as simple as to set your dependency to `importlib_resources < 6`, possibly with a minimum that includes the [changes](https://importlib-resources.readthedocs.io/en/latest/history.html) your project needs. This project has flagged those methods as deprecated since [5.3.0](https://importlib-resources.readthedocs.io/en/latest/history.html#v5-3-0) almost two years ago, and the replacement functionality has been nominally available since [1.1.0](https://importlib-resources.readthedocs.io/en/latest/history.html#v1-1-0).

If you were to migrate to the preferred, non-legacy API, you could remove that pin.

I know it's an inconvenience, but such is the price of progress.

Thanks for understanding.
